name: interesting_places
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  collection: 1.19.1
  cupertino_icons: ^1.0.8
  dio: 5.8.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: 2.2.0
  freezed_annotation: ^2.4.1
  introduction_screen: ^3.1.17
  json_annotation: 4.9.0
  path: 1.9.1
  path_provider: 2.1.5
  provider: ^6.1.5
  retrofit: ^4.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.1
  json_serializable: ^6.9.5
  retrofit_generator: ^9.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700